---
- name: Kubernetes API lab - J4
  hosts: all
  gather_facts: no
  vars: 
    - morpheus_endpoint: v7fhrtftc64evbadxxar4nl55m.privatecloud.greenlake.hpe.com
    - api_key: df0b71e2-cdba-4e21-acb3-b15bf21af331
    - group: Default
    - clouds: HPE GreenLake VMaaS Cloud-Trial4
    - user: emam
    #- user: "{{ lookup('env','API_USER') }}"

  tasks:
    - name: create integration
      uri:
        url: https://{{ morpheus_endpoint }}/api/integrations
        method: POST
        validate_certs: no
        return_content: yes
        force_basic_auth: true
        timeout: 60
        headers:
          Authorization: "Bearer {{ api_key }}"
        body: |
          {
            "integration": {
              "name": "{{ user }}-kubernetes-api",
              "enabled": true,
              "type": "ansible",
              "url": "https://github.com/cxteamtrials/bp",
              "config": {
                "ansibleDefaultBranch": "master",
                "ansiblePlaybooks": "kubernetes",
                "ansibleRoles": "",
                "ansibleGroupVars": "",
                "ansibleHostVars": "",
                "ansibleGalaxyEnabled": true,
                "ansibleVerbose": true,
                "ansibleCommandBus": true
              }
            }
          }
        body_format: json
      ignore_errors: yes
      register: integrations

    - name: create ansible tasks - k8s master
      uri:
        url: https://{{ morpheus_endpoint }}/api/tasks
        method: POST
        validate_certs: no
        return_content: yes
        force_basic_auth: true
        timeout: 60
        headers:
          Authorization: "Bearer {{ api_key }}"
        body: |
          {
            "task": {
            "name": "{{ user }}-k8s-master-api",
            "taskType": {
              "code": "ansibleTask"
            },
            "taskOptions": {
              "ansiblePlaybook": "master.yml",
              "ansibleGitId": "{{ integrations.json.integration.id }}"
            },
            "executeTarget": "resource"
          }
          }
        body_format: json
      ignore_errors: yes
      register: tasks_master

    - name: create ansible tasks - k8s worker
      uri:
        url: https://{{ morpheus_endpoint }}/api/tasks
        method: POST
        validate_certs: no
        return_content: yes
        force_basic_auth: true
        timeout: 60
        headers:
          Authorization: "Bearer {{ api_key }}"
        body: |
          {
            "task": {
            "name": "{{ user }}-k8s-worker-api",
            "taskType": {
              "code": "ansibleTask"
            },
            "taskOptions": {
              "ansiblePlaybook": "worker.yml",
              "ansibleGitId": "{{ integrations.json.integration.id }}"
            },
            "executeTarget": "resource"
          }
          }
        body_format: json
      ignore_errors: yes
      register: tasks_worker

    - name: create workflow - k8s master
      uri:
        url: https://{{ morpheus_endpoint }}/api/task-sets
        method: POST
        validate_certs: no
        return_content: yes
        force_basic_auth: true
        timeout: 60
        headers:
          Authorization: "Bearer {{ api_key }}"
        body: |
          {
            "taskSet": {
            "name": "{{ user }}-k8s-master-api",
            "platform": "linux",
            "type": "provision",
            "tasks": [
              {
                "taskId": "{{ tasks_master.json.task.id }}",
                "taskPhase": "provision"
              }
            ]
          }
          }
        body_format: json
      ignore_errors: yes
      register: workflow_master


    - name: create workflow - k8s worker
      uri:
        url: https://{{ morpheus_endpoint }}/api/task-sets
        method: POST
        validate_certs: no
        return_content: yes
        force_basic_auth: true
        timeout: 60
        headers:
          Authorization: "Bearer {{ api_key }}"
        body: |
          {
            "taskSet": {
            "name": "{{ user }}-k8s-worker-api",
            "platform": "linux",
            "type": "provision",
            "tasks": [
              {
                "taskId": "{{ tasks_worker.json.task.id }}",
                "taskPhase": "provision"
              }
            ]
          }
          }
        body_format: json
      ignore_errors: yes
      register: workflow_worker

    - name: create blueprint
      uri:
        url: https://{{ morpheus_endpoint }}/api/blueprints
        method: POST
        validate_certs: no
        return_content: yes
        force_basic_auth: true
        timeout: 60
        headers:
          Authorization: "Bearer {{ api_key }}"
        body: |
          {
            "name": "{{ user }}-kubernetes-cluster-api",
            "type": "morpheus",
            "tiers": {
              "k8s-master": {
                "instances": [
                  {
                    "instance": {
                      "layout": {
                          "provisionTypeCode": "vmware",
                          "code": "vmware-1.0-single",
                          "instanceVersion": "1.0",
                          "name": "Vmware VM",
                          "id": 569
                        },
                    "environments": {
                      "Test": {
                        "groups": {
                          "{{ group }}": {
                            "clouds": {
                              "{{ clouds }}": {
                                "instance": {
                                  "allowExisting": false,
                                  "type": "vmware",
                                  "layout": {
                                    "code": "vmware-1.0-single",
                                    "id": 569,
                                    "provisionTypeCode": "vmware",
                                    "name": "Vmware VM",
                                    "instanceVersion": "1.0"
                                  },
                                  "environmentPrefix": "KUBE",
                                  "name": "${username}-${groupName}-${sequence+10}",
                                  "allowExisting": false,
                                  "type": "vmware",
                                  "userGroup": {
                                  "id": ""
                                  }
                                },
                                "volumes": [
                                  {
                                    "volumeCustomizable": true,
                                    "vId": 601,
                                    "controllerMountPoint": "636:0:6:0",
                                    "readonlyName": false,
                                    "size": 40,
                                    "maxIOPS": null,
                                    "name": "root",
                                    "rootVolume": true,
                                    "storageType": 1,
                                    "minStorage": 4294967296,
                                    "datastoreId": "auto",
                                    "maxStorage": 42949672960
                                  }
                                ],
                                "scale": {
                                  "typeId": 1,
                                  "instanceThresholdId": ""
                                },
                                "config": {
                                  "template": 601,
                                  "resourcePoolId": 2,
                                  "createUser": true,
                                  "vmwareFolderId": "group-v41",
                                  "expose": 8080,
                                  "noAgent": false
                                },
                                "networkInterfaces": [
                                  {
                                    "ipMode": "",
                                    "primaryInterface": true,
                                    "showNetworkPoolLabel": true,
                                    "showNetworkDhcpLabel": false,
                                    "network": {
                                      "idName": "App-net",
                                      "pool": {
                                        "name": "Blue-Pool",
                                        "id": 1
                                      },
                                      "id": "network-2",
                                      "hasPool": true
                                    },
                                    "networkInterfaceTypeId": 4,
                                    "networkInterfaceTypeIdName": "VMXNET 3"
                                  }
                                ],
                                "workflow": {
                                    "taskSetId": "{{ workflow_master.json.taskSet.id }}"
                                },
                                "plan": {
                                  "code": "G1-Medium",
                                  "id": 403
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                ],
                "tierIndex": 1,
                "tier": {
                  "bootOrder": 0,
                  "lockedFields": [
                    "bootOrder"
                  ]
                },
                "linkedTiers": [
                  "k8s-worker"
                ]
              },
              "k8s-worker": {
                "instances": [
                  {
                    "instance": {
                      "type": "vmware"
                    },
                    "environments": {
                      "Test": {
                        "groups": {
                          "{{ group }}": {
                            "clouds": {
                              "{{ clouds }}": {
                                "instance": {
                                  "allowExisting": false,
                                  "type": "vmware",
                                  "layout": {
                                    "layout": {
                                      "provisionTypeCode": "vmware",
                                      "code": "vmware-1.0-single",
                                      "instanceVersion": "1.0",
                                      "name": "Vmware VM",
                                      "id": 569
                                    },
                                  "name": "${username}-${groupName}-${sequence+10}"
                                },
                                "group": {
                                  "id": 1
                                },
                                "volumes": [
                                  {
                                    "volumeCustomizable": true,
                                    "vId": 601,
                                    "controllerMountPoint": "636:0:6:0",
                                    "readonlyName": false,
                                    "size": 40,
                                    "maxIOPS": null,
                                    "name": "root",
                                    "rootVolume": true,
                                    "storageType": 1,
                                    "minStorage": 4294967296,
                                    "datastoreId": "auto",
                                    "maxStorage": 42949672960
                                  }
                                ],
                                "config": {
                                  "template": 594,
                                  "createUser": true,
                                  "noAgent": false,
                                  "resourcePoolId": 2
                                },
                                "networkInterfaces": [
                                  {
                                    "ipMode": "",
                                    "primaryInterface": true,
                                    "showNetworkPoolLabel": true,
                                    "showNetworkDhcpLabel": false,
                                    "network": {
                                      "idName": "App-net",
                                      "pool": {
                                        "name": "Blue-Pool",
                                        "id": 1
                                      },
                                      "id": "network-2",
                                      "hasPool": true
                                    },
                                    "networkInterfaceTypeId": 4,
                                    "networkInterfaceTypeIdName": "VMXNET 3"
                                  }
                                ],
                                "scale": {
                                  "typeId": 1,
                                  "instanceThresholdId": 1
                                },
                                "workflow": {
                                    "taskSetId": "{{ workflow_worker.json.taskSet.id }}"
                                },
                                "plan": {
                                  "id": 403
                                  "code": "G1-Medium"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                ],
                "tierIndex": 2,
                "tier": {
                  "bootOrder": 1,
                  "lockedFields": [
                    "bootOrder"
                  ]
                },
                "linkedTiers": [
                  "k8s-master"
                ]
              }
            },
            "description": "test",
            "category": "web",
            "templateImage": ""
          }
        body_format: json
      ignore_errors: yes
