---
- name: Kubernetes API lab - J4
  hosts: all
  gather_facts: no
  vars: 
    - morpheus_endpoint: ""
    - api_key: ""
    - group: ""
    - user: ""
    - clouds: HPE GreenLake VMaaS Cloud-Trial4
  
  tasks:     
    - name: create k8s App from blueprint 
      uri:
        url: https://{{ morpheus_endpoint }}/api/apps
        method: POST
        validate_certs: no
        return_content: yes
        force_basic_auth: true
        timeout: 60
        headers:
          Authorization: "Bearer {{ api_key }}"
        body: |
          {
            "blueprintId": "62",
            "name": "{{ user }}-K8s-APP-api",
            "description": "this a k8s cluster created by api call",
            "group": {
              "{{ group }}"
            }
          }
        body_format: json
      ignore_errors: yes
        
